services:
  backend:
    build:
      context: .
      dockerfile: ./src/dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - .env
    volumes:
      - ./src:/app/src
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    entrypoint: sh -c "
      echo '⏳ Esperando a MySQL...';
      until nc -z db 3306; do
        sleep 1;
      done;
      echo '✅ MySQL está listo. Levantando servidor...';
      npm run dev
      "

  db:
    image: mysql:8.0
    container_name: mini-mercado-db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  backend_node_modules: